name: Build and Push to ECR

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          role-to-assume: arn:aws:iam::575751781353:role/github-actions-ecr-role
          aws-region: ap-south-1
          allowed-account-ids: '575751781353'

      - name: Verify AWS Identity
        run: |
          aws sts get-caller-identity

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t sample-app .

      - name: Tag Docker Image
        run: |
          docker tag sample-app:latest \
            575751781353.dkr.ecr.ap-south-1.amazonaws.com/sample-app:latest

      - name: Push Docker Image
        run: |
          docker push \
            575751781353.dkr.ecr.ap-south-1.amazonaws.com/sample-app:latest
